### ISSUE TITLE
Text based inputs

### ISSUE THREAD

**Issue by dmason1992** [MintyTrebor/BtnCmd#10]
Hey I would love to be able to add text based inputs i.e.
Specify tool dia, Use that input when setting WCS (i.e. offset by tool dia/2)

**Comment by dmason1992** [comment]
Edit this can probably done by using the global variable panel input (found it weird this was a panel not just an option like the buttons)

**Comment by MintyTrebor** [comment]
https://github.com/MintyTrebor/BtnCmd/wiki/Input-Panel
