### ISSUE TITLE
Can't set background colour of custom panel

### ISSUE THREAD

**Issue by dmason1992** [MintyTrebor/BtnCmd#11]
Hi,

I would like to be able to set custom background colours for the custom panels so i can match them to the defaults ones.

![image](https://user-images.githubusercontent.com/12624408/184482788-9beb034c-45bf-40b2-9c71-6e151214417a.png)

In addition setting background colour for input panel causes it to do this rather than just a nice rectangle around the text input section

![image](https://user-images.githubusercontent.com/12624408/184483377-2a0c187b-1fe2-42d9-beb0-6e6a89d24341.png)

**Comment by MintyTrebor** [comment]
You have made the panel to small for the contents : https://github.com/MintyTrebor/BtnCmd/wiki/Add-Edit-Panel#note
Std DWC Panel colours cannot be changed - I use the original DWC panels so they cannot be altered.

**Comment by dmason1992** [comment]
You closed this but you didn't answer the question I would like to change the custom DWC panel to match the originals (currently it has no background just the option for an outline)

**Comment by MintyTrebor** [comment]
Add a static text panel (just put a space in the text field). Then place your items ontop. The static text panel can be set to any colour you like.
![image](https://user-images.githubusercontent.com/26109080/184490496-88ef8dc4-0d99-4cd0-a4eb-26e9b02cd61b.png)

You can then add it to your layout and hide the border
![image](https://user-images.githubusercontent.com/26109080/184490870-6b162824-75e2-4993-8deb-57013038f2f5.png)

**Comment by dmason1992** [comment]
Ah sweet neat workaround. How come text panels can have the background set but not custom ones?

**Comment by MintyTrebor** [comment]
Because a custom panel is essentially an embedded layout. Layout background colours cannot be set manually as they are controlled through DWC by the light/dark mode.

**Comment by dmason1992** [comment]
Cheers thanks for explaining
