### ISSUE TITLE
Prerequisites 

### ISSUE THREAD

**Issue by Gubbfittan** [MintyTrebor/BtnCmd#12]
Hi!
I have DWC 3.4.5 on my duet 2 wifi board, I have downloaded the latest version of BtnCmd (v01.02.02) but i get this error: 
![Duet_fail](https://user-images.githubusercontent.com/74116695/235285304-887b1843-ff3a-41d8-a620-b71fc0996a21.png)

**Comment by MintyTrebor** [comment]
Please read the release notes in the releases page.
