### ISSUE TITLE
Too many decimal places for the selected value

### ISSUE THREAD

**Issue by 3gfisch** [MintyTrebor/BtnCmd#13]
Too many decimal places are displayed for the selected value, see pic
<img width="335" alt="Bildschirmfoto 2023-05-23 um 22 48 59" src="https://github.com/MintyTrebor/BtnCmd/assets/18620991/2c979ea8-2381-4fd2-9a28-76137a09624d">

**Comment by MintyTrebor** [comment]
Are you using the latest version?
![image](https://github.com/MintyTrebor/BtnCmd/assets/26109080/67c3d465-b8d1-4a37-b5a8-15dfae9e84dd)
Plus the latest version also has this option:
![image](https://github.com/MintyTrebor/BtnCmd/assets/26109080/7690f8ac-70ac-4b58-8b3a-2d3b9654724e)
which restricts the number of decimal places to a user defined value
