### ISSUE TITLE
[Bug] : newly created panels don't show up

### ISSUE THREAD

**Issue by nikscha** [MintyTrebor/BtnCmd#14]
**Describe the bug**
When I create a new panel it doesn't show up in the tabs bar. Only the default panel shows up

**Expected behaviour**
I expect the newly created panel to show up in the tabs bar

**Screenshots**
New Panel in edit mode:
![image](https://github.com/MintyTrebor/BtnCmd/assets/38561129/02b4547f-bcb5-49ef-bb7f-32f2739c7f3a)
Once I press exit and save:
![image](https://github.com/MintyTrebor/BtnCmd/assets/38561129/826b6278-3485-4692-bf73-a8b8ddd27866)

**Version Info:**
 - OS: Windows 10
 - Browser Firefox
 - BtnCmd Version 01.02.07 
 - DWC Version  3.5.0-rc.1

**Comment by MintyTrebor** [comment]
A custom panel does not create a new tab, it create a new panel for you to add to an existing/new tab in layout edit mode
https://github.com/MintyTrebor/BtnCmd/wiki/Create-Mode
https://github.com/MintyTrebor/BtnCmd/wiki/Edit-Mode

**Comment by nikscha** [comment]
Thank you, that solved it!
