### ISSUE TITLE
[Bug] : Global input variable numeric not updating on focus change

### ISSUE THREAD

**Issue by SellA** [MintyTrebor/BtnCmd#15]
**Describe the bug**
When a global input variable of numeric type is inserted (numeric field not slider), if you write a number, the only method to confirm/update the global variable is to press enter on the keyboard.

**Expected behaviour**
I would expect that changing focus to another input field or clicking any button (input field loosing focus) would update the global variable. The update when clicking another button in the page would be preferable for what i'm trying to do.

**Screenshots**
![Screenshot 2024-03-03 202607](https://github.com/MintyTrebor/BtnCmd/assets/2340861/8d0ede15-e9b3-4c9d-b539-c8547cac485a)

In the screenshot i have 4 inputs that request movement to the axis when button "Vai" is pressed. These will ignore endstop anc machine limits. I know it's strange but i'm retrofitting and old foam cutting machine and trying to get UI as close as possible as the old software we used back in the days.
If i change one of the four input and press the button "Vai" nothing happens because you have to confirm the changes with enter key while focus is on the input. I would prefer the possibility to update the field when it looses focus or when i press the button "Vai" (i think the latter will probably be achieved implementig the losing focus callback)

**Version Info:**
 - OS: Windows 11
 - Browser: Firefox
 - BtnCmd Version 0.10.15
 - DWC Version 3.4.6

**Comment by MintyTrebor** [comment]
This is by design. Loosing focus in the browser/vue framework is not always a user elective action, it can be just moving your cursor over another object, and many other permutations, which would trigger the update variable action when not desirable. I will double check my code as this was an early design choice, but I think what you require would be a  new feature like a group input panel with a confirm button.

**Comment by MintyTrebor** [comment]
I have added an option to allow you to choose to require enter to accept a new value, or 'on focus change' to accept a new value in the input panel config screen. This will be available in the next release - which is planned for DWC 3.5 release

**Comment by SellA** [comment]
Thanks for that. I can't find any help on building current source to test it out.. can you give me some hints please? I've updated firmware and DWC to latest beta.

**Comment by MintyTrebor** [comment]
https://github.com/Duet3D/DuetWebControl/wiki/Third-Party-Plugins

**Comment by SellA** [comment]
Thanks, i correctly built DWC V3.5 branch and connected to my running board, but i get a lot of complains on vue and vuefy versions when i npm install the packets in your install commands.txt file... i don't really know nothing on that things so i think i'll wait your next build.

Edit: it seems to me that only vue-draggable-resizable is complaining about the DWC version of vue:

PS C:\Users\Michele\Desktop\DuetWebControl-3.5-dev> npm install vue-draggable-resizable
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: duetwebcontrol@3.5.0-rc.3+6
npm ERR! Found: vue@2.7.16
npm ERR! node_modules/vue
npm ERR!   dev vue@"^2.7.16" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer vue@"^3.2.25" from vue-draggable-resizable@3.0.0
npm ERR! node_modules/vue-draggable-resizable
npm ERR!   vue-draggable-resizable@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

Any suggestion? Thanks for your patience

Edit#2: i found in the releases plugin.json that the version of vue-draggable-resizable targeted is 2.3.0 . NPM wanted to install latest 3.0.0. Now i've correctly built the zip and installed into DWC. Work perfectly as i suggested. Really nice work thank you!
