### ISSUE TITLE
[Bug] : Input number slider OM / Gcode

### ISSUE THREAD

**Issue by SellA** [MintyTrebor/BtnCmd#16]
**Describe the bug**
I've setup an input number as a slider and i wanted to write a global variable and, at the same time, run gcode with input value. If i set up linked directly to the global variable it sets it, but it doesn't execute the gcode. If i link to object model and select my global variable from the object model browser, it executes the gcode (also ##VALUE## works correctly) but it doesn't update the global variable value.

**Expected behaviour**
I would expect that in both cases global variable is updated and gcode run if the gcode field is compiled.

**Screenshots**
![immagine](https://github.com/MintyTrebor/BtnCmd/assets/2340861/ff73cc28-78cf-4a4e-809e-77eacd1f2c1e)
In these button i want "Filo ON" to run "M42 P1 S{global.manualMove_wirePower}" (it does) and "Filo OFF" "M42 P1 S0" (it does). The slider should set the global.manualMove_wirePower but also execute "M42 P1 S##VALUE##" gcode after changing the value. Now i can do only the first or the second based on the "link to OM" switch.

**Version Info:**
 - OS: Windows 11
 - Browser: Firefox
 - BtnCmd Version: 01.02.09 (latest source)
 - DWC Version: 3.5.0-rc.3

**Comment by MintyTrebor** [comment]
The link to OM is to estabish a link to a readonly OM key value not a global variable. It is so that you can read the current value of a read only OM key, and then use it to perform any update action you wish.
When not linking to a OM, you only need to enter the name of the global variable, not global.xxxx. eg:
![image](https://github.com/MintyTrebor/BtnCmd/assets/26109080/aa7c8c25-162a-4b7a-91ed-ccbdb5eeb87e)
should work as you describe

**Comment by SellA** [comment]
So i tried to create a simpler slider (without fancy macros call in the post change gcode).


This is my configuration:

![immagine](https://github.com/MintyTrebor/BtnCmd/assets/2340861/495f035d-edab-4bd4-ad2b-68b48d4d754a)

If i put `M42 P1 S{global.manualMove_wirePower}` into the top bar textfield of DWC it works as expected. This is not called when i change the value with the slider. However the global variable is changed.

Am i missing something?

**Comment by MintyTrebor** [comment]
Can you try `M42 P1 S##VALUE## ` instead for the Post Change cmd please.

**Comment by SellA** [comment]
I narrowed down the issue i think. It seems that the command sent to modify the global variable is still running when the gcode is sent. In my case it is skipping the gcode send on function send in file BtnCmdBtnActionFunctions.js .

If in the line `if (code && code.trim() !== '' && !this.doingCode)` i remove the `&& !this.doingCode` the gcode is executed

**Comment by MintyTrebor** [comment]
Hmmm. What control board do you have?? I may have to add a execute delay if certain boards are slower to complete commands.

**Comment by SellA** [comment]
I'm on a Duet2 Wifi.

I think that you could implement a retry function in 'n' ms and retry it for 2 or 3 times before throwing an error.
Another solution would be to queue the commands in a temporary file and execute that file so the duet software should handle the timing i hope.

**Comment by MintyTrebor** [comment]
I'll look into it. Can you also try the alternative cmd I posted earlier please.

**Comment by SellA** [comment]
Also that is not doing anything.
I think i've already tried every combination before digging into the code. Luckily i kept the source for compiling the latest version so it was simple to add some console.log

**Comment by MintyTrebor** [comment]
The code section you mention was originally extracted from DWC main source, so it's entirely possible there has been a  change to how gcode execution is handled in main DWC/RRF since then. I will have to go back and check.

**Comment by MintyTrebor** [comment]
You can also turn on Action Msg's in footer in the global settings, which is intended to show execution msgs when commands are actioned, may help with more immediate feedback.

**Comment by SellA** [comment]
Take your time. At the moment this is only requiring me to use the slider to update the value and then press a button. It's only a step more. I can wait 😊

**Comment by MintyTrebor** [comment]
Fix added to src - will include on next release

**Comment by SellA** [comment]
Nice. I'll give it a go when i come back from work.

**Comment by SellA** [comment]
It's working. This night i can't work on it so i can't tell if it will work as expected in every situation, but it seems that it's working properly.
Thank you!

**Comment by MintyTrebor** [comment]
Great
