### ISSUE TITLE
Button in custom panels configured as "Macro" do not execute macro files.

### ISSUE THREAD

**Issue by radiomodell** [MintyTrebor/BtnCmd#17]
Button Type: Marco do not execute macro files located in standard macro folder when arranged in custom panels.
Former version of BtnCmd (Beta_0.10.03) worked fine.
Button Type: Macro outside of custom panels behave as expected. The configured Macro is executed.
 

![image](https://github.com/MintyTrebor/BtnCmd/assets/26694127/00766158-a12c-42d4-b9df-8a183bd2a2a3)

**Version Info:**
 - Duet 2 Ethernet
 - Browser Chrome
 - BtnCmd Version 01.03.0
 - DWC Version 3.5.1

**Comment by MintyTrebor** [comment]
Thanks for reporting issue. Fixed in latest release.
