### ISSUE TITLE
Any idea why some icons from mdi are not working ?

### ISSUE THREAD

**Issue by Mrdindon** [MintyTrebor/BtnCmd#2]
I tried adding a button with the following icon but it doesn't show up : 

tray-arrow-up from https://materialdesignicons.com

inserted as : 
mdi-tray-arrow-up

same for mdi-tray-arrow-down

At first I tought it was because it had 2 dash in the name but other icons with 2 dashes works great... isn't weird ?

**Comment by MintyTrebor** [comment]
I have experienced it & I could never figure it out. The feature to get the icon is a built in function of the vue framework used by DWC, so it's outside of my control. I've never even seen an error msg show up either - but to be honest it's was a low priority for me so I never took the time to investigate it in any great detail.

**Comment by Mrdindon** [comment]
great :) so I'm not crazy :P I agree this is way below zero priority :)
