### ISSUE TITLE
would it be possible to add the babystep pannel in btncmd ?

### ISSUE THREAD

**Issue by Mrdindon** [MintyTrebor/BtnCmd#3]
Dunno if this is a good place for "feature request :) "

<img width="239" alt="image" src="https://user-images.githubusercontent.com/5002201/134971803-e669727e-b4a8-4215-bfb0-8e8ee9b48710.png">

**Comment by MintyTrebor** [comment]
I can, but I'm not sure it is necessary. You can achieve the same thing by using a standard button using the M290 command.
https://duet3d.dozuki.com/Wiki/M290

**Comment by Mrdindon** [comment]
I agree, but if it's not hard to implement (I really have no idea about that) the nice thing about this panel is that it also reports the current babystep level :) My goal is to have one pane that fits all my need so it's easier to manage from a mobile device without shuffling between the pages :) but as mentionned this would really be a "nice to have" nothing more :)

**Comment by MintyTrebor** [comment]
OK. I'll see if I can add it in the next release. I plan to release the next version when 3.4 moves out of beta.

**Comment by MintyTrebor** [comment]
In the meantime you can show the current babystep level by using a Object model panel with "move.axes[2].babystep" as the model path.

**Comment by MintyTrebor** [comment]
Latest version now includes the Baby Stepping panel (+ a few more)

**Comment by Mrdindon** [comment]
Very Nice 😊

 Thank you Sir !
