### ISSUE TITLE
0.10.02 setting restore from 0.8.20

### ISSUE THREAD

**Issue by kgolger** [MintyTrebor/BtnCmd#5]
Hello!
I removed BtnCmd version 0.8.20 and installed the latest version 0.10.02. DWC and firmware for my Duet2 Wifi (standalone) is currently 3.4.0-b7. I have previously created some menus BtnCmd in the 0.8.20 and the settings were saved as "BtnCmdSettings.json" in  system folder.
Unfortunately I can't find a way to import a backup or perform a restore in the current 0.10.02.

[BtnCmdSettings.json.txt](https://github.com/MintyTrebor/BtnCmd/files/7781054/BtnCmdSettings.json.txt)

![BtnCmd_0 10 02_menu](https://user-images.githubusercontent.com/43003904/147492721-d4a7ff0d-8455-4d4f-b03c-91e9b29b4254.JPG)

did I miss something?

wbr,
Karl

**Comment by MintyTrebor** [comment]
https://github.com/MintyTrebor/BtnCmd/wiki/Navigation

**Comment by kgolger** [comment]
Thanks!
Checked it. However, you can only see these options if you hide the DWC menu bar on the left.

![BtnCmd_backup_1](https://user-images.githubusercontent.com/43003904/147501096-87905d90-c56e-424f-bd56-74026507da4e.JPG)

![BtnCmd_backup_2](https://user-images.githubusercontent.com/43003904/147501127-f5b1c26f-c765-465f-97f1-c0c06b9b96f9.JPG)

wbr,
Karl
