### ISSUE TITLE
Feature Request: Console Viewer

### ISSUE THREAD

**Issue by bradjshannon** [MintyTrebor/BtnCmd#7]
Hey, I'm a huge fan of this plugin! It feels like a missing piece of the core DWC software.

That said, the one functionality that takes me away from my custom interface is the Console. Would it be possible, at a technical level, to make a console viewer within BtnCmd? I don't even need to _send_ commands, just view the outputs.

Thanks for considering this, and thanks for sharing your awesome work.

**Comment by MintyTrebor** [comment]
I'm glad you like it!

I've added a console panel in v0.10.08
