### ISSUE TITLE
Alt Webcam refresh rate

### ISSUE THREAD

**Issue by FPoutre** [MintyTrebor/BtnCmd#9]
Hi, awesome plugin so far !

Sadly, the refresh rate minimum of the Alt Webcam is way to low (5s).
Could you get it lower, maybe to like 100ms ?

Regards,
F/Poutre.

**Comment by MintyTrebor** [comment]
Please try latest version 0.10.10 - I have updated the Alt Web Cam panel to align with recent DWC webcam changes and removed the 5000ms refresh lower limit.
